version: '3.8'
services:
  user_service:
    build:
      context: ./services/user_service
    ports:
      - "5001:5001"

  order_service:
    build:
      context: ./services/order_service
    ports:
      - "5002:5002"
