# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notification.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'notification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12notification.proto\x12\x0cnotification\";\n\x17SendNotificationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"Q\n\x14NotificationResponse\x12\x17\n\x0fnotification_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"1\n\x16GetNotificationRequest\x12\x17\n\x0fnotification_id\x18\x01 \x01(\t2\xd1\x01\n\x13NotificationService\x12]\n\x10SendNotification\x12%.notification.SendNotificationRequest\x1a\".notification.NotificationResponse\x12[\n\x0fGetNotification\x12$.notification.GetNotificationRequest\x1a\".notification.NotificationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENDNOTIFICATIONREQUEST']._serialized_start=36
  _globals['_SENDNOTIFICATIONREQUEST']._serialized_end=95
  _globals['_NOTIFICATIONRESPONSE']._serialized_start=97
  _globals['_NOTIFICATIONRESPONSE']._serialized_end=178
  _globals['_GETNOTIFICATIONREQUEST']._serialized_start=180
  _globals['_GETNOTIFICATIONREQUEST']._serialized_end=229
  _globals['_NOTIFICATIONSERVICE']._serialized_start=232
  _globals['_NOTIFICATIONSERVICE']._serialized_end=441
# @@protoc_insertion_point(module_scope)
