# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order_service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'order_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13order_service.proto\x12\x05order\"K\n\x12\x43reateOrderRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nproduct_id\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\"h\n\rOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x12\n\nproduct_id\x18\x03 \x01(\t\x12\x10\n\x08quantity\x18\x04 \x01(\x05\x12\x0e\n\x06status\x18\x05 \x01(\t\"#\n\x0fGetOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"!\n\x0eMessageRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"!\n\x0fMessageResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xc9\x01\n\x0cOrderService\x12>\n\x0b\x43reateOrder\x12\x19.order.CreateOrderRequest\x1a\x14.order.OrderResponse\x12\x38\n\x08GetOrder\x12\x16.order.GetOrderRequest\x1a\x14.order.OrderResponse\x12?\n\x0eReceiveMessage\x12\x15.order.MessageRequest\x1a\x16.order.MessageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEORDERREQUEST']._serialized_start=30
  _globals['_CREATEORDERREQUEST']._serialized_end=105
  _globals['_ORDERRESPONSE']._serialized_start=107
  _globals['_ORDERRESPONSE']._serialized_end=211
  _globals['_GETORDERREQUEST']._serialized_start=213
  _globals['_GETORDERREQUEST']._serialized_end=248
  _globals['_MESSAGEREQUEST']._serialized_start=250
  _globals['_MESSAGEREQUEST']._serialized_end=283
  _globals['_MESSAGERESPONSE']._serialized_start=285
  _globals['_MESSAGERESPONSE']._serialized_end=318
  _globals['_ORDERSERVICE']._serialized_start=321
  _globals['_ORDERSERVICE']._serialized_end=522
# @@protoc_insertion_point(module_scope)
