# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: comment.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'comment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcomment.proto\x12\x07\x63omment\"I\n\x14\x43reateCommentRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\"X\n\x0f\x43ommentResponse\x12\x12\n\ncomment_id\x18\x01 \x01(\t\x12\x0f\n\x07task_id\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\t\"\'\n\x11GetCommentRequest\x12\x12\n\ncomment_id\x18\x01 \x01(\t2\x9e\x01\n\x0e\x43ommentService\x12H\n\rCreateComment\x12\x1d.comment.CreateCommentRequest\x1a\x18.comment.CommentResponse\x12\x42\n\nGetComment\x12\x1a.comment.GetCommentRequest\x1a\x18.comment.CommentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'comment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATECOMMENTREQUEST']._serialized_start=26
  _globals['_CREATECOMMENTREQUEST']._serialized_end=99
  _globals['_COMMENTRESPONSE']._serialized_start=101
  _globals['_COMMENTRESPONSE']._serialized_end=189
  _globals['_GETCOMMENTREQUEST']._serialized_start=191
  _globals['_GETCOMMENTREQUEST']._serialized_end=230
  _globals['_COMMENTSERVICE']._serialized_start=233
  _globals['_COMMENTSERVICE']._serialized_end=391
# @@protoc_insertion_point(module_scope)
